name: C/C++ CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Just
      run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg cppcheck clang-tidy

    - name: Build
      run: just build

    - name: Run Tests
      run: just test

    - name: Static Analysis
      run: just check

    - name: Integration Test
      run: |
        # Verify help output matches expected regex
        ./build/vhcalc -h | grep -E "Usage: .*vhcalc"
