---
name: Publish Python package to PyPI

on:
    push:
        tags:
            - '*'

jobs:
    publish-pypi-package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Set up Python
              uses: actions/setup-python@main
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python -m pip install -U pip poetry invoke
                  inv env.init-dev --no-pre-commit

            - name: Build package
              run: |
                  inv build.dist

            - name: Publish package
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.pypi_password }}
